services:
  web:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - projeto-network

networks:
  projeto-network:
    external: true